name: gratuity_etl
version: 1.0.0
config-version: 2

profile: gratuity_etl

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

vars:
  auto_gratuity_rate: 0.19

models:
  gratuity_etl:
    staging:
      +schema: gratuity_staging
      +materialized: view
    intermediate:
      +schema: gratuity_staging
      +materialized: view
    marts:
      +schema: gratuity_marts
      +materialized: table
